id: '491'
name: Test website
locales:
  - en
  - it
theme: null
domain: null
internalDomain: broken-butterfly-2396.admin.datocms.com
noIndex: false
globalSeo:
  siteName: null
  titleSuffix: null
  facebookPageUrl: null
  twitterAccount: null
  fallbackSeo: null
favicon: null
faviconMetaTags:
  - tagName: meta
    attributes:
      name: application-name
      content: Test website